import moment from 'moment-timezone';
import fetch from 'node-fetch';
const handler = async (m, { conn, args }) => {
   const res = await fetch('https://api.github.com/repos/Karim-off/DylanBot1');
   const json = await res.json();
   let txt = `╭─────────────────────╮`;
      txt += `│  *乂 ＤＹＬＡＮ - ＢＯＴ 乂*\n`;
      txt += `│\n`;
      txt += `│  *𝑵𝒐𝒎𝒃𝒓𝒆:* ${json?.name || 'DylanBot'}\n`;
      txt += `│  *𝑽𝒊𝒔𝒊𝒕𝒂𝒏𝒕𝒆𝒔:* ${json?.watchers_count || '-'}\n`;
      txt += `│  *𝑻𝒂𝒎𝒂𝒏𝒐:* ${(json?.size / 1024).toFixed(2) || '-'} MB\n`;
      txt += `│  *𝑨𝒄𝒕𝒖𝒂𝒍𝒊𝒛𝒂𝒄𝒊𝒐𝒏:* ${moment(json?.updated_at).format('DD/MM/YY') || '-'}\n`;
      txt += `◦  *𝑰𝒈:* https://www.instagram.com/usxr_angelito`;
      txt += `╰─────────────────────╯`;
   await conn.sendMessage(m.chat, {text: txt.trim(), mentions: [...txt.matchAll(/@([0-9]{5,16}|0)/g)].map((v) => v[1] + '@s.whatsapp.net'), contextInfo: {forwardingScore: 9999999, isForwarded: true, mentionedJid: [...txt.matchAll(/@([0-9]{5,16}|0)/g)].map((v) => v[1] + '@s.whatsapp.net'), "externalAdReply": {"showAdAttribution": true, "containsAutoReply": true, "renderLargerThumbnail": true, "title": global.titulowm2, "containsAutoReply": true, "mediaType": 1, "thumbnail": imagen6, "mediaUrl": global.md, "sourceUrl": global.md}}}, {quoted: m});
};
handler.help = ['scbot'];
handler.tags = ['info'];
handler.command = /^(sc|scbot|scrip|script)$/i;
export default handler;